# -*- coding: utf-8 -*-
"""CatBoostPaper_FinalNoMildOversampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWwVoCy9QCtgPaBLhu0Yrd5dv_oN4nFV
"""

# ========================================
#  Higher Education Students Performance – CatBoostClassifier model, Particle Swarm Optimization, and SHAP
#  Predictive and Interpretable Machine Learning Model for Modeling Students' Final Grade
# ========================================
"""
This research aims to share insights and knowledge regarding the development of a
predictive and interpretable machine learning model, CatBoostClassifier,
for predicting students' end-of-term final grades and
explaining the model’s predictions employing SHAP, an explainable AI method.
As well as share the process of tuning CatBoostClassifier hyperparameters using
Particle Swarm Optimization (PSO), a population-based metaheuristic algorithm,
with repeated 3-fold stratified cross-validation.

Dataset: The dataset used in this study is the "Higher Education Students
Performance Evaluation" dataset, collected from the Faculty of Engineering and
the Faculty of Educational Sciences students in 2019.
Source: Yilmaz, N. & Şekeroğlu, B. (2019). Higher Education Students Performance
Evaluation [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C51G82.
The dataset is a 145 x 33 table of categorical/integer data, where each column
corresponds to a question or attribute, and each row corresponds to a student.
Questions 1-10 are personal questions, questions 11-16 are family questions,
and questions 17-30 cover the student's education habits.
DATA.csv does not contain any helper columns that need to be dropped or broken down into multiple columns.
The target column is GRADE, the student's end-of-term output grade
(0: Fail, 1: DD, 2: DC, 3: CC, 4: CB, 5: BB, 6: BA, 7: AA). All remaining columns
(personal questions, family questions, education habit questions, and COURSE ID)
are used as categorical features, except STUDENT ID, which was dropped: it is
unique per row (145 distinct values for 145 students), so it carries no
generalizable signal and would only add noise/overfitting risk.

Symmetries & Asymmetries: Although the questionnaire exhibited structural symmetry in questionnaire design
through questions with a predefined set of answers, the response distribution for
question GRADE showed strong asymmetry, with the highest-engagement
category '1' being 4.375 times more than the lowest-engagement category '0'.
This was heavily imbalanced, which resulted in biased predictions.
The distribution of the GRADE target column is checked
below via a value count. Class imbalance across the eight grade categories is
expected, since some grades are naturally awarded far more often than others,
which can result in biased predictions if left unaddressed.

All stages of the study, including data loading, preprocessing,
model optimization, training, evaluation metrics, and interpretability,
were implemented in Python and executed in the Google Colab environment.
"""

# =====================================================================================
# PROFESOROV FEEDBACK (doslovan copy-paste teksta dobijenog od profesora na prethodnu
# verziju ovog rada). Svaka izmena u kodu koja odgovara na ovaj feedback oznacena je
# komentarom "KOREKCIJA (kom. N)" gde N odgovara broju komentara ispod (grep "KOREKCIJA"
# za sva mesta u fajlu).
# =====================================================================================
#
# "Rad je dobar i vidi se da ste uložili dosta truda. Pisan je malo hrabrije, no što
# treba da bude pisan studentski istraživački rad. Dakle, treba biti realniji-oprezniji
# u interpretaciji rezultata. Ja ću vam navesti nekoliko zamerki, pa vi razmislite i
# vidite kako ćete odgovoriti i poboljšati svoj seminarski."
#
# --- KOMENTAR 1 (-> KOREKCIJA kom. 1 u kodu: bootstrap intervali pouzdanosti) ---
# "Prva hipoteza govori o značajnom poboljšanju, a zaključak tvrdi da su sve tri makro
# metrike kod oba optimizovana modela bolje; međutim, ponovljeni CV model ima
# makro-preciznost 0,2061 naspram 0,2933 kod baznog modela. Možda napisati da je prva
# hipoteza delimično potvrđena, precizno navesti koje metrike jesu, a koje nisu
# poboljšane, i izbaciti „značajno" ako nema statističkog testa. Još bolje bi bilo dati
# intervale pouzdanosti ili rezultate preko više nezavisnih ponavljanja."
#
# --- KOMENTAR 2 (-> KOREKCIJA kom. 2 u kodu: podela pre PSO-a, CV nad trening skupom) ---
# "Konačna evaluacija na jednom test skupu od samo 29 studenata je preslaba za jače
# zaključke. Sa osam klasa neke klase u test skupu imaju samo dva ili tri predstavnika,
# pa jedna jedina pogrešna predikcija drastično menja precision, recall i F1. To vidite
# i sami. Dodatno, metodološki tok treba napisati potpuno nedvosmisleno: prvo
# train/test podela, a zatim PSO i sve odluke o hiperparametrima isključivo na
# trening skupu; trenutni opis prvo predstavlja CV/PSO, a tek kasnije train/test
# podelu, iako kasnija diskusija govori o 116 trening primera. Razmisliti da se ponovi
# ceo eksperiment preko, recimo, 10-20 različitih spoljašnjih stratifikovanih podela
# ili primeniti nested/repeated CV i izvestiti srednju vrednost ± standardnu devijaciju
# ili interval pouzdanosti."
#
# --- KOMENTAR 3 (-> KOREKCIJA kom. 3 u kodu: ablaciona analiza) ---
# "Poređenje sa baznim modelom ne omogućava da se utvrdi šta je zapravo donelo
# poboljšanje. Optimizovani pristup istovremeno uvodi balansirane težine klasa, PSO
# hiperparametre i ensemble od pet modela sa soft voting-om, dok je baseline
# podrazumevani CatBoost bez balansiranja. Tako se ne zna da li rezultat dolazi od
# PSO-a, class weights-a ili ensemble-a. Predlažem da napravite malu ablation tabelu:
# default CatBoost; CatBoost + class weights; CatBoost + class weights + PSO;
# CatBoost + class weights + PSO + ensemble. Ako se rešite da radite master rad onda
# bi čak jedan ili dva dodatna standardna modela, npr. Random Forest ili Logistic
# Regression, značajno ojačala eksperimentalni deo."
#
# --- KOMENTAR 4 (-> KOREKCIJA kom. 4 u kodu: SHAP preko svih 5 modela ansambla) ---
# "SHAP analiza ne objašnjava potpuno isti model koji se koristi za konačne
# predikcije. Konačni rezultat dobija se soft voting-om pet nezavisnih CatBoost
# modela, ali se SHAP računa samo za prvi od tih pet modela zato što je uzet kao
# „reprezentativan". To je metodološki problem: objašnjava se jedan član ansambla, a
# ne finalni prediktor. Pored toga, tvrdnja da je model „robustniji" ili
# „interpretabilno bogatiji" zato što koristi svih 31 obeležje nije nužno opravdana —
# korišćenje većeg broja obeležja može značiti i korišćenje šuma. Rad trenutno
# zaključuje da je ponovljeni CV model robusniji upravo na osnovu takvog argumenta.
# Možda bi trebalo agregirati SHAP vrednosti preko svih pet modela ili raditi
# interpretaciju modela koji se zasebno evaluira kao finalni model; „robustniji"
# koristiti samo ako je to pokazano stabilnošću rezultata kroz više eksperimenata."
# =====================================================================================



#-----------------------------------------------------Installing & importing libraries
"""
This cell installs dependencies when run in Google Colab (the `!pip install` line
below is a Colab/IPython shell escape, not valid standalone Python, and Colab starts
each session with a fresh environment so it needs reinstalling every time). When
running this script locally instead, install the same dependencies once from a
terminal and skip this line:
    pip install catboost pyswarms joblib scikit-learn pandas numpy matplotlib seaborn shap
"""
try:
    import google.colab  # only importable inside Google Colab
    IN_COLAB = True
    get_ipython().system('pip install --quiet catboost pyswarms joblib')
except ImportError:
    IN_COLAB = False  # running locally (plain .py script or local Jupyter)

import pandas as pd
import numpy as np
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split, StratifiedKFold, RepeatedStratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, log_loss, classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import matplotlib.pyplot as plt
import pyswarms as ps
from joblib import Parallel, delayed



#-----------------------------------------------------
# PREPROCESSING
#-----------------------------------------------------
print("\n\n============ PREPROCESSING... ============")

"""
The dataset was read from the CSV file and stored as a DataFrame object (df).
In Colab, DATA.csv is read from Google Drive (mounted first). Running locally,
DATA.csv is read from the working directory instead - place it next to this
script, or edit DATA_PATH below to point at wherever it lives on disk.
"""
if IN_COLAB:
    from google.colab import drive
    drive.mount("/content/gdrive")
    DATA_PATH = "/content/gdrive/MyDrive/DATA.csv"
else:
    DATA_PATH = "DATA.csv"
df = pd.read_csv(DATA_PATH)
"""
STUDENT ID was dropped: it is unique per row (one value per student), so it carries
no generalizable signal and would only add noise/overfitting risk to the model.
"""
df_clean = df.drop(columns=['STUDENT ID'])
print("STUDENT ID column dropped (unique per row, no generalizable signal)")
"""The categorical target was defined as GRADE, while all remaining columns as categorical features."""
target_col = 'GRADE'
print("Target column:", target_col)
#This will show True in any column where hidden whitespace exists:
#(df_clean.astype(str) != df_clean.astype(str).apply(lambda col: col.str.strip())).any()
#if everything is false:
X = df_clean.drop(columns=[target_col]).astype(str)  #features
y = df_clean[target_col].astype(str)                 #target
#if something is true:
#X = df_clean.drop(columns=[target_col]).astype(str).applymap(lambda v: v.strip())
#y = df_clean[target_col].astype(str).apply(lambda v: v.strip())
"""
The categorical target values were encoded using LabelEncoder to transform class labels into
integer labels suitable for multi-class classification.
The original class labels were preserved for prediction inter-pretation and evaluation metrics.
"""
le = LabelEncoder()
y_enc = le.fit_transform(y)
class_labels = list(le.classes_)
print("Encoded classes (model order):", class_labels)
feature_names = list(X.columns)
print("Feature names:", feature_names)
cat_features = list(range(X.shape[1]))
print("Categorical features:", cat_features)
"""
A target value count was performed, and the presence of a large class imbalance was determined.
In order to mitigate the effects of target class imbalance, balanced class weights were computed
(and they are incorporated into the CatBoost training process
to ensure the model learns from all classes fairly.)
"""
print("Balansirano: najveca klasa <= 2-2,5 puta najmanje klase; klase imaju slican broj primera")
print("Umereno balansirano: najveca klasa > 3-4 puta najmanje klase")
print("Veoma nebalansirano: najveca klasa === 5-10 puta najmanje klase; klasa ima < 20-30 primera")
print("balanced classes?: \n{}\n".format(df_clean[target_col].value_counts()))
# '1' majority
# '0' minority
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_enc),
    y=y_enc
)
print("Class weights:", class_weights)










#-----------------------------------------------------
# METAHEURISTIC OPTIMIZATION
# Particle Swarm Optimization (PSO) was employed to identify an optimal learning rate, depth, and L2 regularization.
#-----------------------------------------------------
print("\n\n============ Particle Swarm Optimization (PSO)... ============")

"""
The custom parallelized fitness function simultaneously evaluated
all hyperparameter sets proposed by the optimizer and returned their performance scores.
The custom parallelized fitness function evaluates hyperparameters by
training temporary CatBoost models using stratified cross-validation.

To ensure reproducibility, a fixed random seed was used throughout all hyperparameter evaluations.

Stratified K-fold cross-validation with three folds, repeated three times (9 fold
evaluations in total), was applied to enforce symmetry in the target class distribution
across folds. With only 145 students spread across 8 grade classes (the rarest class has
just 8 members), a single 3-fold split gives a highly noisy macro-F1 estimate per particle,
which makes PSO chase noise rather than a genuine signal. Repeating the split three times
with different random folds and averaging the score over all 9 evaluations gives PSO a
much more stable fitness target to climb, increasing the chance of converging on a
hyperparameter combination that generalizes rather than one that happened to look good on
a single lucky/unlucky split. With cross-validated model training, overfitting was reduced
to a single train/test split, and each particle was evaluated using repeated 3-fold
stratified cross-validation.

KOREKCIJA (kom. 2): the repeated 3-fold CV inside the fitness function now runs ONLY over
the training set (X_train / y_train), which is carved out BEFORE PSO. The 29-sample test
set is never seen during hyperparameter search.
"""
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# PROFESOR (kom. 2), doslovan citat: "...metodološki tok treba napisati potpuno
# nedvosmisleno: prvo train/test podela, a zatim PSO i sve odluke o hiperparametrima
# isključivo na trening skupu; trenutni opis prvo predstavlja CV/PSO, a tek kasnije
# train/test podelu..." (pun tekst komentara 2 na vrhu fajla)
# ===== KOREKCIJA (kom. 2): podela na trening/test skup PRE optimizacije rojem cestica =====
# Zamerka profesora: PSO je ranije radio unakrsnu validaciju nad CELIM skupom (X, y_enc),
# a tek posle PSO-a se izdvajao test skup od 29 studenata iz istih podataka -> hiperparametri
# su "videli" test skup (curenje podataka). Ispravka: test skup se izdvaja OVDE, pre PSO-a,
# istim random_state-om (dakle isti 29-clani test skup kao ranije), i NIJEDNA odluka o
# hiperparametrima od ove tacke ne sme koristiti X_test / y_test.
X_train, X_test, y_train, y_test = train_test_split(
    X, y_enc, test_size=0.2, stratify=y_enc, random_state=RANDOM_STATE
)
print("\n[KOREKCIJA kom.2] Trening skup: {} studenata | Test skup: {} studenata "
      "(test skup se NE koristi ni u PSO-u ni za rano zaustavljanje)".format(len(X_train), len(X_test)))
# ===== KRAJ KOREKCIJE (kom. 2) =====

kf = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=RANDOM_STATE)  # 9 fold evals for a more stable fitness signal
def pso_objective_parallel(particles):
    def evaluate_particle(p):
        lr = float(p[0])
        depth = int(round(p[1]))
        l2 = int(round(p[2]))
        random_strength = float(p[3])
        fold_scores = []

        # ===== KOREKCIJA (kom. 2): unakrsna validacija SAMO nad trening skupom =====
        # Ranije: kf.split(X, y_enc) -> preklopi su ukljucivali i buduci test skup.
        # Sada: kf.split(X_train, y_train) -> PSO ocenjuje hiperparametre iskljucivo na
        # trening podacima; train_idx/test_idx su interni preklopi UNUTAR trening skupa.
        # (kraj korekcije kom. 2 -- v. sledece 3 linije)
        for train_idx, test_idx in kf.split(X_train, y_train):
            X_tr, X_te = X_train.iloc[train_idx], X_train.iloc[test_idx]
            y_tr, y_te = y_train[train_idx], y_train[test_idx]

            """
            CatBoost’s optimized data structure, Pool,
            was used to store features, labels, and cate-gorical features.
            """
            tr_pool = Pool(X_tr, y_tr, cat_features=cat_features)
            te_pool = Pool(X_te, y_te, cat_features=cat_features)

            """
            Temporary CatBoostClassifier models were configured with
            PSO-tuned learning_rate, depth, l2_leaf_reg, and random_strength,
            500 iterations, ‘MultiClass’ loss_function,
            ‘Mul-tiClass’ eval_metric, fixed random_seed,
            previously calculated balanced class_weights,
            and 50 early_stopping_rounds.
            random_strength adds randomness to split selection, which acts as extra
            regularization and helps the search find hyperparameters that resist
            overfitting on this small, noisy dataset.
            """
            model = CatBoostClassifier(
                iterations=500,  # smaller for speed
                learning_rate=lr,
                depth=depth,
                l2_leaf_reg=l2,
                random_strength=random_strength,
                loss_function='MultiClass',
                eval_metric='MultiClass',
                random_seed=RANDOM_STATE,
                early_stopping_rounds=50,
                verbose=False,
                class_weights=class_weights,
                thread_count=-1,   # use all cores
                allow_writing_files=False   # avoids catboost_info/ dir races across parallel joblib workers
            )
            model.fit(tr_pool, eval_set=te_pool, use_best_model=True)
            preds = np.argmax(model.predict_proba(te_pool), axis=1)
            """
            The performance was measured using the mean macro F1-score,
            suitable for class imbalance because it treats all classes equally.
            """
            fold_scores.append(f1_score(y_te, preds, average='macro'))

        """Minimizing the mean macro F1-score across folds resulted in max-imizing Macro F1."""
        return -np.mean(fold_scores)

    # Parallel evaluation of all particles
    return np.array(Parallel(n_jobs=-1)(delayed(evaluate_particle)(p) for p in particles))

"""PSO search space was defined in the code as parameter bounds
from 0.01 to 0.10 for learning rate,
from 3 to 10 for depth,
from 1 to 10 for L2 regularization,
from 0 to 5 for random_strength (added regularization dimension)
"""
bounds = (
    np.array([0.01, 3, 1, 0.0]),
    np.array([0.10, 10, 10, 5.0])
)
"""
*The optimizer was implemented using the Global Best topology
with 10 particles, 4 dimensions, defined parameter bounds, and set options.
*The custom parallelized fitness function^^^ simultaneously evaluated
all hyperparameter sets proposed by the optimizer and returned their performance scores.
The optimizer relied on those performance scores for returning the
optimal-performing hyperparameter combination after 15 iterations.
*The number of particles and iterations was chosen to balance optimization
quality and computational efficiency.
"""
optimizer = ps.single.GlobalBestPSO(
    n_particles=10,
    dimensions=4,
    options={'c1':1.4, 'c2':1.4, 'w':0.7},
    bounds=bounds
)
cost, pos = optimizer.optimize(pso_objective_parallel, iters=15)  # more thorough search
best_params = {
    'learning_rate': float(pos[0]),
    'depth': int(round(pos[1])),
    'l2_leaf_reg': int(round(pos[2])),
    'random_strength': float(pos[3])
}
print("\nBest parameters found by PSO after 15 iterations:")
print(best_params)








#-----------------------------------------------------
# Oprimized CatBoostClassifier model
#-----------------------------------------------------
print("\n\n============ Oprimized CatBoostClassifier model... ============")

# ===== KOREKCIJA (kom. 2): podela na trening/test je premestena IZNAD PSO bloka =====
# Ranije je train_test_split(X, y_enc, ...) bio ovde (posle PSO-a). Sada se X_train/X_test/
# y_train/y_test prave pre PSO-a (v. KOREKCIJA kom.2 na pocetku), pa je ova podela uklonjena.
# Za rano zaustavljanje (early stopping) finalnih modela koristi se INTERNI validacioni skup
# izdvojen iz trening skupa -- test skup se i dalje ne dodiruje.
X_fit, X_val, y_fit, y_val = train_test_split(
    X_train, y_train, test_size=0.2, stratify=y_train, random_state=RANDOM_STATE
)
print("[KOREKCIJA kom.2] Rano zaustavljanje na internom val skupu: "
      "{} za treniranje, {} za validaciju (iz trening skupa)".format(len(X_fit), len(X_val)))
# ===== KRAJ KOREKCIJE (kom. 2) =====
"""
In this study, five CatBoostClassifier models were independently trained with
a different random seed and identical optimized hyperparameters,
which ensures performance differences came only from randomness.
"""
models = []
for seed in [0, 1, 2, 3, 4]:
    m = CatBoostClassifier(
        iterations=2000,
        learning_rate=best_params['learning_rate'],
        depth=best_params['depth'],
        l2_leaf_reg=best_params['l2_leaf_reg'],
        random_strength=best_params['random_strength'],
        loss_function='MultiClass',
        eval_metric='MultiClass',
        random_seed=seed,
        early_stopping_rounds=100,
        verbose=False,
        class_weights=class_weights,
        allow_writing_files=False
    )
    # ===== KOREKCIJA (kom. 2): rano zaustavljanje na INTERNOM val skupu, ne na test skupu =====
    # Ranije: eval_set = Pool(X_test, y_test, ...) + use_best_model=True -> broj iteracija se
    # birao gledajuci u test skup (curenje). Sada: eval_set = interni val skup (X_val/y_val)
    # izdvojen iz trening skupa. Test skup ostaje netaknut do konacne evaluacije.
    m.fit(
        Pool(X_fit, y_fit, cat_features=cat_features),
        eval_set=Pool(X_val, y_val, cat_features=cat_features),
        use_best_model=True
    )
    # ===== KRAJ KOREKCIJE (kom. 2) =====
    models.append(m)

"""
Final predictions were obtained with a soft voting approach by averaging
class probabilities across models, which reduced prediction variance and
improved robustness, particularly for minority classes.
"""
probs = np.mean( #soft voting (%,%,%,%,%,%,%,%)
    [m.predict_proba(Pool(X_test, y_test, cat_features=cat_features)) for m in models],
    axis=0
)
y_pred = np.argmax(probs, axis=1)#averaging
"""
A function was defined to display class prediction
probabilities of the first test sample
as a percentage for individual samples.
"""
def pretty_probs(probs, labels):
    return {labels[i]: f"{round(100*probs[i],2)}%" for i in range(len(labels))}
print("\nExample probabilities for first test sample:")
print(pretty_probs(probs[0], class_labels))








#-----------------------------------------------------
# Evaluation metrics
#-----------------------------------------------------
print("\n\n============ Evaluation metrics... ============")
acc = accuracy_score(y_test, y_pred)
ll = log_loss(y_test, probs)
macro_f1 = f1_score(y_test, y_pred, average='macro')
macro_precision = precision_score(y_test, y_pred, average="macro", zero_division=0)
macro_recall = recall_score(y_test, y_pred, average="macro", zero_division=0)
print(f"Accuracy: {acc:.4f}")
print(f"Log-loss: {ll:.4f}")
print(f"Macro F1: {macro_f1:.4f}")
print(f"Macro-Precision: {macro_precision:.4f}")
print(f"Macro-Recall   : {macro_recall:.4f}")
#Kako da znaš da li balansacija menja performanse modela?
#A) Pogledaj classification report po klasama:
# Vidi se visoka preciznost za najbrojniju GRADE klasu
# Vidi se niska preciznost/recall za retke GRADE klase
# === To znaci da se model "oslanja" na najbrojniju klasu i da bi balansacija pomogla
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=class_labels))
#B) Pogledaj konfuzionu matricu
# Ako vidiš da model sve gura u jednu klasu → nebalansirano
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
print(confusion_matrix(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# PROFESOR (kom. 1), doslovan citat: "...zaključak tvrdi da su sve tri makro metrike kod
# oba optimizovana modela bolje; međutim, ponovljeni CV model ima makro-preciznost 0,2061
# naspram 0,2933 kod baznog modela... izbaciti „značajno" ako nema statističkog testa.
# Još bolje bi bilo dati intervale pouzdanosti ili rezultate preko više nezavisnih
# ponavljanja." (pun tekst komentara 1 na vrhu fajla)
# ===== KOREKCIJA (kom. 1): bootstrap intervali pouzdanosti (test skup = 29 studenata) =====
# Zamerka profesora: rad tvrdi "znacajno poboljsanje" bez ikakvog testa znacajnosti, a test
# skup od 29 uzoraka je premali za jake zakljucke. Ovde se dodaju bootstrap 95% intervali
# pouzdanosti (2.5 / 50 / 97.5 percentil) racunati resemplovanjem 29 test redova sa
# ponavljanjem N=2000 puta iz VEC izracunatih predikcija -- bez ponovnog treniranja.
BOOT_N = 2000
_boot_rng = np.random.default_rng(RANDOM_STATE)

def _metrics_from(y_true_arr, y_pred_arr, y_proba_arr):
    return {
        "accuracy":  accuracy_score(y_true_arr, y_pred_arr),
        "log_loss":  log_loss(y_true_arr, y_proba_arr, labels=list(range(len(class_labels)))),
        "macro_f1":  f1_score(y_true_arr, y_pred_arr, average="macro", zero_division=0),
        "macro_precision": precision_score(y_true_arr, y_pred_arr, average="macro", zero_division=0),
        "macro_recall":    recall_score(y_true_arr, y_pred_arr, average="macro", zero_division=0),
    }

def bootstrap_ci(y_true_arr, y_pred_arr, y_proba_arr, n=BOOT_N):
    y_true_arr = np.asarray(y_true_arr); y_pred_arr = np.asarray(y_pred_arr).ravel()
    y_proba_arr = np.asarray(y_proba_arr)
    keys = ["accuracy", "log_loss", "macro_f1", "macro_precision", "macro_recall"]
    acc = {k: [] for k in keys}
    m = len(y_true_arr)
    for _ in range(n):
        idx = _boot_rng.integers(0, m, m)
        if len(np.unique(y_true_arr[idx])) < 2:   # degenerate resample -> skip
            continue
        r = _metrics_from(y_true_arr[idx], y_pred_arr[idx], y_proba_arr[idx])
        for k in keys:
            acc[k].append(r[k])
    return {k: (np.percentile(v, 2.5), np.percentile(v, 50), np.percentile(v, 97.5)) for k, v in acc.items()}

def print_ci(title, ci):
    print("\n--- {} ---".format(title))
    for k, (lo, med, hi) in ci.items():
        print("  {:<16}: {:.4f}   95% CI [{:.4f}, {:.4f}]".format(k, med, lo, hi))

# sacuvati optimizovane predikcije PRE nego sto ih bazni model prepise nize
y_pred_opt = np.asarray(y_pred).ravel().copy()
probs_opt = np.asarray(probs).copy()

print("\n\n============ [KOREKCIJA kom.1] Bootstrap 95% CI - optimizovani ansambl ============")
ci_opt = bootstrap_ci(y_test, y_pred_opt, probs_opt)
print_ci("Optimizovani model (soft-voting ansambl)", ci_opt)
# ===== KRAJ KOREKCIJE (kom. 1) =====


















#-----------------------------------------------------
# SHAP-based feature importance
#-----------------------------------------------------
print("\n\n============ SHAP... ============")

"""
SHAP values and CatBoost’s built-in feature importance were
used to interpret the CatBoostClassifier model predictions.
Because SHAP is model-specific, the first model was used as a representative model.
The training data was converted into Pool format and used for computing SHAP values.
The mean absolute SHAP values were calculated across all samples and
classes to obtain global feature importance scores.
These values were compared with CatBoost’s built-in feature importance to ensure con-sistency.
Multi-class output was handled by producing one global importance value per feature.
The feature importance table was created with feature names, SHAP im-portance,
and CatBoost’s built-in feature importance, displaying all questions.
The table was sorted by SHAP importance.

KOREKCIJA (kom. 4): SHAP vrednosti i ugradjena vaznost obelezja se vise NE racunaju samo
za models[0], nego za svih 5 modela ansambla i zatim se USREDNJAVAJU -- time se objasnjava
upravo finalni prediktor (soft-voting ansambl), a ne jedan njegov clan.
"""
train_pool = Pool(X_train, y_train, cat_features=cat_features)
n_features = len(feature_names)

# PROFESOR (kom. 4), doslovan citat: "Konačni rezultat dobija se soft voting-om pet
# nezavisnih CatBoost modela, ali se SHAP računa samo za prvi od tih pet modela zato što
# je uzet kao „reprezentativan". To je metodološki problem: objašnjava se jedan član
# ansambla, a ne finalni prediktor... Možda bi trebalo agregirati SHAP vrednosti preko
# svih pet modela..." (pun tekst komentara 4 na vrhu fajla)
# ===== KOREKCIJA (kom. 4): agregacija SHAP-a i CatBoost vaznosti preko svih 5 modela ansambla =====
_per_model_sv = []          # po-model (n_samples, n_classes, n_features) SHAP nizovi
_per_model_mean_shap = []
_per_model_mean_abs_shap = []
_per_model_cb = []
for _m in models:
    _sv = np.asarray(_m.get_feature_importance(train_pool, type='ShapValues'))[:, :, :-1]  # bez baseline stuba
    _per_model_sv.append(_sv)
    _per_model_mean_shap.append(np.mean(_sv, axis=(0, 1)))
    _per_model_mean_abs_shap.append(np.mean(np.abs(_sv), axis=(0, 1)))
    _cbr = np.array(_m.get_feature_importance(train_pool, type='FeatureImportance'))
    if len(_cbr) != n_features:
        _nc = len(_cbr) // n_features
        _cbr = _cbr.reshape(_nc, n_features).sum(axis=0)
    _per_model_cb.append(_cbr)

# usrednjeno preko 5 modela = objasnjenje finalnog (soft-voting) prediktora
mean_shap = np.mean(_per_model_mean_shap, axis=0)
mean_abs_shap = np.mean(_per_model_mean_abs_shap, axis=0)
cb_importance = np.mean(_per_model_cb, axis=0)
# standardna devijacija preko 5 modela = mera stabilnosti vaznosti unutar ansambla
mean_abs_shap_std = np.std(_per_model_mean_abs_shap, axis=0)
cb_importance_std = np.std(_per_model_cb, axis=0)
# usrednjeni po-uzorak SHAP niz za dependence/histogram grafike nize
shap_vals_no_base = np.mean(_per_model_sv, axis=0)

_stab = pd.DataFrame({
    'feature': feature_names,
    'mean_abs_shap': mean_abs_shap,
    'mean_abs_shap_std_across_5': mean_abs_shap_std,
    'cb_importance': cb_importance,
    'cb_importance_std_across_5': cb_importance_std,
}).sort_values('mean_abs_shap', ascending=False)
print("\n[KOREKCIJA kom.4] Vaznost obelezja usrednjena preko 5 modela (+ st. devijacija preko 5):")
print(_stab.head(12).to_string(index=False))
# ===== KRAJ KOREKCIJE (kom. 4) =====

fi_df_mas = pd.DataFrame({
    'feature': feature_names,
    'mean_shap': mean_shap,
    'mean_abs_shap': mean_abs_shap,
    'cb_importance': cb_importance
}).sort_values('mean_abs_shap', ascending=False)

fi_df_ms = pd.DataFrame({
    'feature': feature_names,
    'mean_shap': mean_shap,
    'mean_abs_shap': mean_abs_shap,
    'cb_importance': cb_importance
}).sort_values('mean_shap', ascending=False)

fi_df_cb = pd.DataFrame({
    'feature': feature_names,
    'mean_shap': mean_shap,
    'mean_abs_shap': mean_abs_shap,
    'cb_importance': cb_importance
}).sort_values('cb_importance', ascending=False)

print(f"\nAll features influencing {target_col} - sort(mas):")
print(fi_df_mas)
print(f"\nAll features influencing {target_col} - sort(ms):")
print(fi_df_ms)
print(f"\nAll features influencing {target_col} - sort(cb):")
print(fi_df_cb)

#mas
plt.figure(figsize=(8,10))
plt.barh(fi_df_mas.feature, fi_df_mas.mean_abs_shap, alpha=0.6, label='Mean |SHAP|')
plt.barh(fi_df_mas.feature, fi_df_mas.mean_shap, alpha=0.6, label='Mean SHAP')
plt.barh(fi_df_mas.feature, fi_df_mas.cb_importance, alpha=0.4, label='CatBoost Importance')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()
#ma
plt.figure(figsize=(8,10))
plt.barh(fi_df_ms.feature, fi_df_ms.mean_abs_shap, alpha=0.6, label='Mean |SHAP|')
plt.barh(fi_df_ms.feature, fi_df_ms.mean_shap, alpha=0.6, label='Mean SHAP')
plt.barh(fi_df_ms.feature, fi_df_ms.cb_importance, alpha=0.4, label='CatBoost Importance')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()
#cb
plt.figure(figsize=(8,10))
plt.barh(fi_df_cb.feature, fi_df_cb.mean_abs_shap, alpha=0.6, label='Mean |SHAP|')
plt.barh(fi_df_cb.feature, fi_df_cb.mean_shap, alpha=0.6, label='Mean SHAP')
plt.barh(fi_df_cb.feature, fi_df_cb.cb_importance, alpha=0.4, label='CatBoost Importance')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()

#-----separate----
plt.figure(figsize=(8,10))
plt.barh(fi_df_mas.feature, fi_df_mas.mean_abs_shap, alpha=0.6, label='Mean |SHAP|')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,10))
plt.barh(fi_df_ms.feature, fi_df_ms.mean_shap, alpha=0.6, label='Mean SHAP')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,10))
plt.barh(fi_df_cb.feature, fi_df_cb.cb_importance, alpha=0.4, label='CatBoost Importance')
plt.gca().invert_yaxis()
plt.xlabel("Feature Importance")
plt.title(f"Influential Features for {target_col}")
plt.legend()
plt.tight_layout()
plt.show()







#To understand how weekly study hours (column "17") influence predictions:

import shap
class_idx = 1  # positive class
shap_class = shap_vals_no_base[:, class_idx, :]  # (n_samples, n_features)
shap.dependence_plot(
    "17",
    shap_class,
    X_train,
    feature_names=feature_names
)

#or check distribution:
study_hours_idx = feature_names.index("17")
plt.hist(shap_class[:, study_hours_idx], bins=50)
plt.title("SHAP value distribution for weekly study hours - column 17 (class 1)")
plt.xlabel("SHAP value")
plt.ylabel("Frequency")
plt.show()







"""
 The default CatBoostClassifier model, without hyperparameter tuning or class re-balancing,
 was run to establish a baseline for PSO and optimized model evaluation.
 The model was trained using the same data split and metrics.
 It uses the same Pool/cat_features setup as the optimized model so that categorical
 encoding is handled identically and the only real differences between baseline and
 optimized model are PSO tuning, class balancing, and the 5-seed ensemble.
"""
from catboost import CatBoostClassifier
from sklearn.metrics import (accuracy_score, log_loss, f1_score, precision_score, recall_score, classification_report, confusion_matrix)

# ---------------------------
# Default CatBoost Baseline
# ---------------------------
baseline_model = CatBoostClassifier(
    random_state=42,
    verbose=0,
    allow_writing_files=False
)
baseline_model.fit(Pool(X_train, y_train, cat_features=cat_features)) # Train
baseline_test_pool = Pool(X_test, y_test, cat_features=cat_features)
y_pred = baseline_model.predict(baseline_test_pool) # Predict
baseline_probs = baseline_model.predict_proba(baseline_test_pool) # needed for its own log-loss

# ---------------------------
# Evaluation Metrics
# ---------------------------
print("\n=== Default CatBoost Baseline ===")
acc = accuracy_score(y_test, y_pred)
ll = log_loss(y_test, baseline_probs)
macro_f1 = f1_score(y_test, y_pred, average="macro")
macro_precision = precision_score(y_test, y_pred, average="macro", zero_division=0)
macro_recall = recall_score(y_test, y_pred, average="macro", zero_division=0)
print(f"Accuracy: {acc:.4f}")
print(f"***Log-loss: {ll:.4f}")
print(f"Macro-F1       : {macro_f1:.4f}")
print(f"Macro-Precision: {macro_precision:.4f}")
print(f"Macro-Recall   : {macro_recall:.4f}")

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred, zero_division=0))

print("\n=== Confusion Matrix: ===")
# Ako vidiš da model sve gura u jednu klasu → nebalansirano
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
print(confusion_matrix(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# ===== KOREKCIJA (kom. 1): bootstrap CI za bazni model + uparena razlika optimizovani - bazni =====
baseline_pred = np.asarray(y_pred).ravel().copy()
baseline_proba = np.asarray(baseline_probs).copy()
print("\n\n============ [KOREKCIJA kom.1] Bootstrap 95% CI - bazni (default) model ============")
ci_base = bootstrap_ci(y_test, baseline_pred, baseline_proba)
print_ci("Bazni model (default CatBoost)", ci_base)

print("\n--- Uparena bootstrap razlika (optimizovani - bazni), isti resemplovani test skup ---")
_yt = np.asarray(y_test)
_keys = ["accuracy", "log_loss", "macro_f1", "macro_precision", "macro_recall"]
_pair_rng = np.random.default_rng(RANDOM_STATE)
_diffs = {k: [] for k in _keys}
_m = len(_yt)
for _ in range(BOOT_N):
    _idx = _pair_rng.integers(0, _m, _m)
    if len(np.unique(_yt[_idx])) < 2:
        continue
    _ro = _metrics_from(_yt[_idx], y_pred_opt[_idx], probs_opt[_idx])
    _rb = _metrics_from(_yt[_idx], baseline_pred[_idx], baseline_proba[_idx])
    for _k in _keys:
        _diffs[_k].append(_ro[_k] - _rb[_k])
for _k in _keys:
    _d = np.array(_diffs[_k])
    # za log_loss "bolje" znaci nize -> udeo resemplova gde je optimizovani nizi
    _better = np.mean(_d < 0) if _k == "log_loss" else np.mean(_d > 0)
    print("  {:<16}: razlika median {:+.4f}   95% CI [{:+.4f}, {:+.4f}]   udeo resemplova u korist optimizovanog: {:.1%}".format(
        _k, np.percentile(_d, 50), np.percentile(_d, 2.5), np.percentile(_d, 97.5), _better))
print("NAPOMENA: ovo NIJE formalni test znacajnosti; sluzi samo kao gruba mera pouzdanosti razlike "
      "na test skupu od svega 29 studenata.")
# ===== KRAJ KOREKCIJE (kom. 1) =====


# PROFESOR (kom. 3), doslovan citat: "Poređenje sa baznim modelom ne omogućava da se
# utvrdi šta je zapravo donelo poboljšanje... Predlažem da napravite malu ablation
# tabelu: default CatBoost; CatBoost + class weights; CatBoost + class weights + PSO;
# CatBoost + class weights + PSO + ensemble." (pun tekst komentara 3 na vrhu fajla)
# ===== KOREKCIJA (kom. 3): ablaciona analiza - koja komponenta donosi poboljsanje =====
# Zamerka profesora: optimizovani pristup istovremeno uvodi (a) balansirane tezine klasa,
# (b) PSO hiperparametre i (c) ansambl od 5 modela sa soft-voting-om, dok je bazni model
# default CatBoost bez ijedne od te tri komponente -> ne zna se sta je donelo poboljsanje.
# Ablacija dodaje komponente jednu po jednu:
#   A) default CatBoost                         (= bazni model)
#   B) + balansirane tezine klasa
#   C) + PSO hiperparametri (jedan model)
#   D) + ansambl 5 modela sa soft-voting-om     (= optimizovani model)
print("\n\n============ [KOREKCIJA kom.3] Ablaciona analiza ============")

def _eval_block(name, y_true_arr, y_pred_arr, y_proba_arr):
    r = _metrics_from(np.asarray(y_true_arr), np.asarray(y_pred_arr).ravel(), np.asarray(y_proba_arr))
    print("  {:<58} acc={:.4f}  logloss={:.4f}  macroF1={:.4f}  macroP={:.4f}  macroR={:.4f}".format(
        name, r["accuracy"], r["log_loss"], r["macro_f1"], r["macro_precision"], r["macro_recall"]))
    return r

# A) default CatBoost (bez tezina, bez PSO, bez ansambla)
_A = CatBoostClassifier(random_state=RANDOM_STATE, verbose=0, allow_writing_files=False)
_A.fit(Pool(X_train, y_train, cat_features=cat_features))
_eval_block("A) default CatBoost (= bazni)", y_test,
            _A.predict(baseline_test_pool), _A.predict_proba(baseline_test_pool))

# B) + balansirane tezine klasa
_B = CatBoostClassifier(random_state=RANDOM_STATE, verbose=0, allow_writing_files=False,
                        class_weights=class_weights)
_B.fit(Pool(X_train, y_train, cat_features=cat_features))
_eval_block("B) + balansirane tezine klasa", y_test,
            _B.predict(baseline_test_pool), _B.predict_proba(baseline_test_pool))

# C) + PSO hiperparametri (jedan model, isto rano zaustavljanje kao finalni ansambl)
_C = CatBoostClassifier(
    iterations=2000,
    learning_rate=best_params['learning_rate'],
    depth=best_params['depth'],
    l2_leaf_reg=best_params['l2_leaf_reg'],
    random_strength=best_params['random_strength'],
    loss_function='MultiClass', eval_metric='MultiClass',
    random_seed=0, early_stopping_rounds=100, verbose=False,
    class_weights=class_weights, allow_writing_files=False
)
_C.fit(Pool(X_fit, y_fit, cat_features=cat_features),
       eval_set=Pool(X_val, y_val, cat_features=cat_features), use_best_model=True)
_eval_block("C) + PSO hiperparametri (jedan model)", y_test,
            _C.predict(baseline_test_pool), _C.predict_proba(baseline_test_pool))

# D) + ansambl 5 modela sa soft-voting-om (= optimizovani model, vec izracunat gore)
_eval_block("D) + ansambl 5 modela, soft voting (= optimizovani)", y_test, y_pred_opt, probs_opt)
print("NAPOMENA: PSO hiperparametri (best_params) su nasledjeni iz gornje optimizacije; "
      "ablacija ne pokrece PSO ponovo.")
# ===== KRAJ KOREKCIJE (kom. 3) =====








#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Data verification from AI project
#DataFrame object
print(type(df))
print("Loaded:", df.shape)
print("Columns:", list(df.columns))
#uzorak data seta:
print("head: \n{}\n".format(df_clean.head())) #print(df_clean[0:5]) #ispisi prvih 5 redova iz dataframe-a
print("tail: \n{}\n".format(df_clean.tail)) #ispisivanje poslednjih 5 redova
#indeksi pocinju od 0, korak je 1,
print("index: {}\n".format(df_clean.index))
print("1. red dataframe-a: \n{}\n".format(df_clean.iloc[0])) #1. red dataframe-a
#dimenzija dataframe-a (2D):
print("DataFrame ima %d dimenzije" % df_clean.ndim)
#ispisi featur-e/kolone, target-e/labele, vrednosti
print("Featurs/Kolone: ", df_clean.columns)
print(f"Odgovori za {target_col} (target/label variable): ", df_clean[target_col].unique())
print("Vrednosti: \n", df_clean.values) #prosledjuje samo vrednosti
#koliko ima redova i kolona
(row, col) = df_clean.shape
print("Dataframe ima %d zapisa/redova i %d obelezja/kolona(labels)\n" % (row, col))
print("Dataframe ima %d zapisa/redova i %d obelezja/kolona(labels)\n" % (len(df_clean), len(df_clean.columns)))
#transponovan dataframe
print("Transponovan dataframe: \n{}".format(df_clean.T))
#sve max i min vrednosti kolona
import numpy as np
max = df_clean.apply(np.max)
min = df_clean.apply(np.min)
print("max vrednosti kolona: \n{}\n".format(max))
print("min vrednosti kolona: \n{}\n".format(min))
print(df_clean.info())
print("(.info) --- Zakljucak:\nDataFrame ima %d redova i %d kolona\nVidimo kako su imenovane kolone\nKolone imaju int podatke (int64)\nsvaka kolona ima non-null vrednosti, tj. nemamo nedostajuce vrednosti\n" % (row, col))
print(df_clean.describe()) #osnovne statisticke podatke
print("(.describe) --- Zakljucak:\ncount: broj non-null podataka za svaku kolonu, nemamo prazna polja\nmean(avg): srednja vrednost svakog pitanja\nstd(standardna devijacija): disperzija vrednosti svake kolone oko mean, veci std ukazuje na vecu disperziju oko mean vrednosti\nmin,max: najmanja i najveca vrednost za svaku kolonu\n%: distribucija podataka, npr 25% ispitanika je izabralo odredjenu vrednost za odredjeno pitanje\n")
print(df_clean.corr())
print(f"(.corr) --- Zakljucak:\nprocena stepena linearnog odnosa izmedju 2 numbericke variable\nblizu 1: jaka pozitivna linearna veza, v1 se povecava kako se v2 povecava\nblizu-1: jaka negativna linearna veza, v1 se povecava kako se v2 povecava\nblizu 0: slaba ili nikakva linearna veza\npogledati korelacije kolona sa {target_col}\n")
